server:
  port: 8090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
logging:
  level:
    org:
      hibernate:
        type:
          descripteor:
            sql: trace